---
- hosts: eodrh7
  become: yes
  become_method: sudo
  roles:
    - {role: iptables, when: "iptables_config"}
    - {role: common, when: "install_glusterfs"}
    - {role: epel, when: "use_epel and not 'production' in group_names"}
    - emacs
    - jdk
    - odbc
    - postgresql-client
  post_tasks:
    - name: install libselinux-python
      become: yes
      become_method: sudo
      yum:
        name: libselinux-python
        state: present


