---
- hosts: eodrh7
  become: yes
  become_method: sudo
#  roles:
#    - {role: iptables, when: "iptables_config"}
#    - {role: common, when: "install_glusterfs"}
#    - {role: epel, when: "use_epel and not 'production' in group_names"}
#    - emacs
#    - jdk
#    - odbc
#    - postgresql-client
#  post_tasks:
  tasks:
    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: present
    - name: copy ecs local to remote
      copy:
        src: files/ecs-13.8.9-linux-x64.bin 
        dest: /opt
        owner: root
        group: root
        mode: 0755

#   - name: install ecs
#     command: /opt/ecs-13.8.9-linux-x64.bin


- hosts: eodapp7
  become: yes
  become_method: sudo
  tasks:
    - name: install libselinux-python
      become: yes
      become_method: sudo
      yum:
        name: libselinux-python
        state: present


