---
- hosts: eodrh7
  become: yes
  become_method: sudo
#  roles:
#    - {role: iptables, when: "iptables_config"}
#    - {role: common, when: "install_glusterfs"}
#    - {role: epel, when: "use_epel and not 'production' in group_names"}
#    - emacs
#    - jdk
#    - odbc
#    - postgresql-client
#  post_tasks:
  tasks:
    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: present
    - name: copy ecs local to remote
      copy:
        src: files/ecs-13.8.9-linux-x64.bin 
        dest: /opt
    - name: groupinstall Desktop
      yum:
        name: "@GNOME Desktop"
        state: present
    - name: set GUI at startup
      command: systemctl set-default graphical.target    

#   - name: install ecs
#     command: /opt/ecs-13.8.9-linux-x64.bin
#   - name: group install "General Purpose Desktop"

#   - name: group install "X Window System"

#   - name: replace /etc/gdm/custom.conf

#   - name: add /etc/X11/xorg.conf

#   - name: edit /Exceed../conf/admin/cluster.cfg
  
#   - name: add rules to /etc/sysconfig/iptables

#   - name: modify /etc/inittab

#   - name: ensure S26haldaemon in /etc/rc5.d

#   - name: modify /usr/local/Exceed../conf/admin/Xconfig/XDMCP_Query.cfg

- hosts: eodapp7
  become: yes
  become_method: sudo
  tasks:
    - name: install libselinux-python
      become: yes
      become_method: sudo
      yum:
        name: libselinux-python
        state: present


