---
- hosts: eodrh7
  become: yes
  become_method: sudo
# pre_tasks:
#   - name: Install iptables-services
#     yum:
#       name: iptables-services
#       state: present
    
#   - name: Make sure firewalld is masked
#     systemd:
#       name: firewalld
#       masked: yes
    
#   - name: Enable iptables services
#     systemd:
#       name: "{{ item }}"
#       state: started
#       enabled: yes
#     with_items:
#       - iptables
#       - ip6tables

  roles:
    - eod7
